/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import controlador.Controlador_Camping;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author alumno
 */
public class Interfaz_Reserva extends javax.swing.JFrame {
    private Controlador_Camping c;
    private DefaultListModel modeloParcelas;
    /**
     * Creates new form Interfaz_Reserva
     */
    public Interfaz_Reserva(Controlador_Camping camp) {
        initComponents();
        c=camp;
        ArrayList parcelas = c.getParcelas();
        modeloParcelas = new DefaultListModel();
        for(Object item : parcelas)
            modeloParcelas.addElement(item);
        
        lista_parcelas.setModel(modeloParcelas);
    }
    
    public Interfaz_Reserva(Controlador_Camping camp,Object parcela)
    {
        initComponents();
        c=camp;
        ArrayList parcelas = c.getParcelas();
        parcelas.remove(parcela);
        modeloParcelas = new DefaultListModel();
        for(Object item : parcelas)
            modeloParcelas.addElement(item);
        
        lista_parcelas.setModel(modeloParcelas);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCarrito = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_parcelas = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonCarrito.setText("Carrito");
        botonCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCarritoMouseClicked(evt);
            }
        });
        botonCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarritoActionPerformed(evt);
            }
        });

        lista_parcelas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista_parcelas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_parcelasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista_parcelas);

        jButton2.setText("Salir");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonCarrito)
                        .addGap(92, 92, 92)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCarritoActionPerformed

    private void botonCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCarritoMouseClicked
        Interfaz_Carrito carr = new Interfaz_Carrito(c);
        carr.setLocationRelativeTo(this);
        carr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCarritoMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Interfaz_Cliente ii = new Interfaz_Cliente(c);
        this.setVisible(false);
        ii.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void lista_parcelasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_parcelasValueChanged
        if(!evt.getValueIsAdjusting()){
            Object parcela = lista_parcelas.getSelectedValue();
            Interfaz_Select_Parcela sel = new Interfaz_Select_Parcela(c,parcela);
            sel.setLocationRelativeTo(this);
            sel.setVisible(true);
        }
    }//GEN-LAST:event_lista_parcelasValueChanged


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCarrito;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista_parcelas;
    // End of variables declaration//GEN-END:variables
}
